furiends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # Login and Sign UP page
    path('', views.index, name='login'),
    path('logged_In/', views.login_auth, name='login_page'),
    path('accounts/signup/', views.signup, name='signup'),

    # Main pages including Home, About
    path('home/<int:user_id>/', views.home, name='home'),
    path('about/', views.about, name='about'),

    # Profile based templates and routes
    path('my_profile/<int:user_id>/', views.my_profile, name='my_profile'), 
    path('my_profile/<int:user_id>/add_photo/', views.add_photo, name='add_photo'),
    path('my_profile/<int:post_id>/', views.post_detail, name='post_detail'),

    # Post Create and Delete based routes views and templates
    path('post/create/<int:user_id>/photo/<int:photo_id>/', views.PostCreate, name='post_create'),
    path('post/create/<int:user_id>/post/photo/<int:photo_id>/', views.PostCreateComment, name='post_create_comment'),
    path('post/create/<int:user_id>/post/<int:post_id>/delete//photo/<int:photo_id>/', views.PostCreateDelete, name='post_create_delete'),

    # likes add and delete
    path('post/create/<int:user_id>/post/<int:post_id>/likes/photo/<int:photo_id>/', views.Likes_Create_Delete, name='like_create_delete'),
    path('post/create/<int:user_id>/post/<int:post_id>/total_likes/photo/<int:photo_id>/', views.total_likes, name='total_likes'),


    #  likes for PHOTO add and delete
    path('post/create/<int:user_id>/likes/photo/<int:photo_id>/', views.create_photo_like, name='photo_like'),
    path('post/create/<int:user_id>/likes/photo/<int:photo_id>/delete/', views.delete_photo, name='photo_delete')
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
TYPE = (
   (1, 'Profile'),
   (2, 'Pets')
)

class Photo(models.Model):
  url = models.CharField(max_length=200)
  caption = models.CharField(max_length=250)
  category = models.IntegerField(choices=TYPE)
  date = models.DateTimeField(default=datetime.now())
  likes = models.BigIntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for post_id: {self.caption} with {self.likes} uploaded on {self.date} by user {self.user}"
  
# Comment Model
class Post(models.Model):
    caption = models.TextField(max_length=250)
    date = models.DateTimeField(default=datetime.now())
    likes = models.BigIntegerField()   
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for post_id: {self.caption} created by user {self.user} on {self.date}"
    
class Post_User(models.Model):
   user_id = models.BigIntegerField()
   post_id = models.BigIntegerField()

   def __str__(self):
      return f'Foreign key between user_id {self.user_id} and post_id {self.post_id}'
     
    
class Photo_User(models.Model):
   user_id = models.BigIntegerField()
   photo_id = models.BigIntegerField()

   def __str__(self):
      return f'Foreign key between user_id {self.user_id} and post_id {self.photo_id}'
     

main_app/forms.py
from django import forms
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Photo, Post


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Mandatory.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Mandatory.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def get_absolute_url(self):
        return reverse('home', kwargs={'user_id': self.id})

class PictureForm(CreateView):
    model = Photo
    fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
import uuid
import boto3
# from django.db.models import RawSQL
from .models import Photo,Post, Post_User, Photo_User
from django.views.generic import ListView, DetailView, CreateView
# Add the two imports below
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from .forms import PictureForm
from datetime import date
from django.utils import timezone 
from django.db import connection
from django.views.decorators.csrf import csrf_exempt

BUCKET = 'furiends'
S3_BASE_URL = f'https://{BUCKET}.s3.ca-central-1.amazonaws.com'


def home(request, user_id):
    user_instance = User.objects.get(pk=user_id)
    user_pic = None
    picture_form = PictureForm()
    query_photo_like = """
        select photo_id, count(photo_id) photo_count from main_app_photo_user group by photo_id
    """
    with connection.cursor() as cursor:
      cursor.execute(query_photo_like)
      columns = [col[0] for col in cursor.description]
      photo_like = [dict(zip(columns, row)) for row in cursor.fetchall() ]
    query_comment = """
        select mp.id, mp.photo_id, mp.user_id, mp.caption, au.username from main_app_post mp
        left join auth_user au
        on mp.user_id = au.id
        order by mp.photo_id, mp.id desc
         """
    with connection.cursor() as cursor:
      cursor.execute(query_comment)
      columns = [col[0] for col in cursor.description]
      comments = [dict(zip(columns, row)) for row in cursor.fetchall() ]
    query_liked = """
        select ap.*, pu.user_id liked, au.username  from main_app_photo ap
        left join 
        (select * from main_app_photo_user where user_id = %s) pu
        on ap.id = pu.photo_id
        left join auth_user au
        on ap.user_id = au.id
        where ap.category = 2
        order by ap.id desc
    """
    with connection.cursor() as cursor:
      cursor.execute(query_liked, [user_id])
      columns = [col[0] for col in cursor.description]
      photo = [dict(zip(columns, row)) for row in cursor.fetchall() ]
    
    try:
        user_pic = Photo.objects.filter(user = user_instance, category=1)[0]
    except:
        pass
    like_comment = Photo_User.objects.all()
    try: 
        photos_profile = Photo.objects.filter(category=1)
        return render(request, 'home.html', {
        'picture_form': picture_form, 'user_id': user_id, 'photo': photos_profile, 'posts': photo, 'photo_like': photo_like,
        'username': user_instance.username, 'user_pic': user_pic, 'comments': comments, 'like_comment': like_comment
    })
    except:
        # print(photos_profile)
        return render(request, 'home.html', {
        'picture_form': picture_form, 'user_id': user_id, 'posts': photo, 'username': user_instance.username, 'user_pic': user_pic, 'comments': comments})


def PostCreate(request, user_id, photo_id):
  photos = Photo.objects.get(pk=photo_id)
  username = User.objects.get(pk=user_id)
#   user_instance = User.objects.get(pk=user_id)
#   posts = Post.objects.filter(photo=photos).order_by('-id')
  query = """
         select mp.*, au.first_name, aa.count total_likes, mapu.post_id like_by_user from main_app_post mp
            left join (
                select post_id, count(post_id) count from main_app_post_user group by post_id
	            ) aa
                on mp.id = aa.post_id
            left join auth_user au
	            on mp.user_id = au.id
            left join 
	        (select * from main_app_post_user  where user_id = %s) mapu
	        on mp.id = mapu.post_id
            where mp.photo_id = %s
                order by id desc
         """
  with connection.cursor() as cursor:
      cursor.execute(query, [user_id, photo_id])
      columns = [col[0] for col in cursor.description]
      posts = [dict(zip(columns, row)) for row in cursor.fetchall() ]
  return render(request, 'picture_comment.html', {'photos': photos, 
                                                  'user_id': user_id, 'posts':posts, 'photo_id': photo_id, 'username': username})


def create_photo_like(request, user_id, photo_id):
    try:
        Photo_User.objects.get(user_id=user_id, photo_id=photo_id).delete()
    except:
        Photo_User.objects.create(user_id = user_id, photo_id=photo_id)
    return redirect(f"/home/{user_id}/")


def delete_photo(request, user_id, photo_id):
    user_instance = User.objects.get(pk=user_id)
    photo_instance = Photo.objects.get(pk=photo_id)
    try:       
        for post in Post.objects.filter(photo=photo_instance):
            Post_User.objects.filter(post_id = post.id).delete()

        Photo_User.objects.filter(photo_id=photo_id).delete()
        
        Photo.objects.filter(pk=photo_id).delete()
        return redirect(f"/home/{user_id}/")
    except:
        return redirect(f"/home/{user_id}/")

@csrf_exempt
def index(request):
    # category = request.POST.get('category')
    # user_instance = User.objects.get(pk=user_id)
    photos = Photo.objects.all()
    # photos =Photo.objects.filter(category=category, user=user_instance)
    # print(photos.reverse())
    return render(request, "registration/login.html", {'photos': photos})

@csrf_exempt
def login_auth(request):
    print(request.POST)
    username = request.POST['username']
    password = request.POST['password']
    user_id = User.objects.get(username=username)
    # print(user_id.id)
    user = authenticate(request, username=username, password=password)
    if user is not None:
        return redirect(f'/home/{user_id.id}/')
        # Redirect to a success page.
    else:
        return redirect('/')
    
# def delete_photo(request, photo_id):
#     Photo.objects.delete(pk=photo_id)
#     return redirect('home.html')

def PostCreateDelete(request, user_id, post_id, photo_id):
    print(user_id, post_id)
    user_instance = User.objects.get(pk=user_id)
    Post.objects.filter(pk=post_id, user=user_instance).delete()
    try:
        Post_User.objects.filter(user_id=user_id, post_id=post_id).delete()
        return redirect(f"/post/create/{user_id}/photo/{photo_id}/")
    except:
        return redirect(f"/post/create/{user_id}/photo/{photo_id}/")

def add_photo(request, user_id):
    photo_file = request.FILES.get('photo-file', None)
    caption = request.POST.get('caption')
    category = request.POST.get('category')
    user_instance = User.objects.get(pk=user_id)

    if request.method == 'POST': 
        # to remove old profile pic and update it with the new one
        if category == '1':
            print('coming to this')
            Photo.objects.filter(user=user_instance, category=category).delete()
        # for photo upload
        if photo_file:
            s3 = boto3.client('s3')
            key = 'furiends/' + uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
            try:
                s3.upload_fileobj(photo_file, BUCKET, key)
                url = f"{S3_BASE_URL}/{key}"
                # print(url)
                # print(user_id)            
                user = User.objects.get(pk=user_id)
                # print(user)
                # print(type(date.today()))
                Photo.objects.create(url=url, user=user_instance, caption=caption, likes=0, category=category)
                # print('done')
            except:
                print('An error occurred uploading file to S3')
        return redirect(f'/home/{user_id}/')
    else:
        return redirect(f'/home/{user_id}/')

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def about(request):
    return render(request, 'about.html')

def my_profile(request, user_id):
    photo = None
    photos = None
    user_instance = User.objects.get(pk=user_id)
    try:
        photo = Photo.objects.filter(user_id=user_instance, category=1)[0]
    except:
        pass
    try:
        photos = Photo.objects.filter(user_id=user_instance, category=2)
    except:
        pass
    
    return render(request, 'my_profile.html', {'user_id': user_id, 'photo': photo, 'photos': photos})

def post_detail(request, post_id):
  post = Post.objects.get(id=post_id)
  return render(request, 'my_profile/post_detail.html', {'post': post
  })

def add_picture(request, user):
    form = PictureForm(request.POST)
    if form.is_valid():
        new_picture = form.save(commit=False)
        new_picture.picture_id = user
        new_picture.save()
    return render('home.html')

@csrf_exempt  
def PostCreateComment(request, user_id, photo_id):
    if request.method == 'POST' and request.POST.get('comment'):
        post = request.POST.get('comment')
        user = User.objects.get(pk=user_id)
        photos = Photo.objects.get(pk=photo_id)
        Post.objects.create(caption=post, likes=0, user=user, photo=photos)
        return redirect(f"/post/create/{user_id}/photo/{photo_id}/")
    else:
        return redirect(f"/post/create/{user_id}/photo/{photo_id}/")
    

def Likes_Create_Delete(request, user_id, post_id, photo_id):
    # print(user_id, post_id)
    try:
        Post_User.objects.get(user_id=user_id, post_id=post_id).delete()
    except:
        Post_User.objects.create(user_id = user_id, post_id=post_id)
    return redirect(f"/post/create/{user_id}/photo/{photo_id}/")

def total_likes(request, user_id, post_id, photo_id):
    return redirect(f"/post/create/{user_id}/photo/{photo_id}/")

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About Furiends</h1>
<hr />
<p>Best Pet Social platform in the WORLD!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>FURIENDS</title>
    <!-- <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet"> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
      integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}" />
    <link rel="stylesheet" href="{% static 'css/my_profile.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/ScrollTrigger.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid" id="nav_new">
        {% if user_id %}
        <a class="navbar-brand" href="{% url 'home' user_id %}"
          ><img src="{% static 'images/Furiends_Logo.png' %}" alt="Furiends"
        /></a>
        {% else %}
        <a class="navbar-brand" href="/"
          ><img src="{% static 'images/Furiends_Logo.png' %}" alt="Furiends"
        /></a>
        {% endif %}
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if user_id %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' user_id %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my_profile' user_id %}"
                >My Profile</a>
            </li>
            <li class="nav-item" id="last_child">
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'signup' %}"
                >Sign Up</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<div id="homepage-container">
  <div id="sidebar">
    {% if user_id %}
      <div id="user-info">
        {% if user_pic.url %}
          <img id="pfp" src="{{ user_pic.url }}" alt="pfp" >
        {% else %}
          <img src="https://furiends.s3.ca-central-1.amazonaws.com/furiends/blank-profile-picture-973460_1280.webp" alt="no pfp">
        {% endif %}
        {{ username }}
      </div>
    {% endif %}
  </div>
  <div id="feed-container" class="feed-container">
    {% for post in posts %}
      <div id="post-container">
        <br>
        {% for picture in photo %}
          
          {% if picture.user.username == post.username %}
            {{ post.username }}
            <div id="post-user-info">
              <img src="{{ picture.url }}" id="post-pfp">
            </div>
          {% endif %}
        {% endfor %}
        <a href="{% url 'post_create' user_id post.id %}">
        <img src="{{post.url}}" id="post-photos" alt="">
        </a>
        <div id="like-photo">
              {% if post.liked %}
              <a href="{% url 'photo_like' user_id post.id %}">
                <div id="liked">Liked</div>
              </a>
              {% else %}
              <a href="{% url 'photo_like' user_id post.id %}">
                <div id="like">Like</div>
              </a>
              {% endif %}
          {% for like in photo_like %}
            {% if like.photo_id == post.id %}
              <div id="count">{{ like.photo_count }}</div>
            {% endif %}
          {% endfor %}
        </div>
        <div id="caption"><h6>{{ post.username }}</h4>: {{ post.caption }}</div>
        <div id="comment-section">
          {% for comment in comments %}
            {% if post.id == comment.photo_id %}
              <div id="comment"><span id="comment-username">{{comment.username}}:</span> {{ comment.caption }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endfor %}
    
  </div>
</div>

<script>
  let like = document.getElementById('like');
  like.onclick = function () {
    like.classList.toggle("liked");
  };

  let sidebar1 = document.querySelector(".feed-container");
  
  let toppy1 = localStorage.getItem("sidebar-scroll");
  if (toppy1 !== null) {
    sidebar1.scrollTop = parseInt(toppy1, 10);
  }

  window.addEventListener("beforeunload", () => {
    localStorage.setItem("sidebar-scroll", sidebar1.scrollTop);
  });
</script>
{% endblock %}

main_app/templates/my_profile.html
{% extends 'base.html' %} {% block content %}

<main>
  <div class="my_profile">
    <div class="card-container px-2 pt-5">
      <img src="{{ photo.url }}" alt="profile photo" class="round" />
      <br />
      <h2 class="userName">{{photo.user}}</h2>
      <br />

      <form
        action="{% url 'add_photo' user_id %}"
        enctype="multipart/form-data"
        method="post"
      >
        {% csrf_token %}
        <div class="mb-3">
          <label for="" class="form-label"></label>
          <input type="file" name="photo-file" class="form-control" />
        </div>
        <div class="mb-3">
          <label for="id_caption" class="form-label">Caption:</label>
          <input
            class="form-control"
            type="text"
            name="caption"
            maxlength="250"
            required=""
            id="id_caption"
          />
        </div>
        <div class="mb-3">
          <label for="id_category" class="form-label">Category:</label>
          <select
            name="category"
            required=""
            id="id_category"
            class="form-select"
          >
            <option value="" selected="">---------</option>

            <option value="1">Profile</option>

            <option value="2">Pets</option>
          </select>
        </div>
        <!-- <table class="inputs">
          <tbody>
            <tr>
              <th><label for="id_caption">Caption:</label></th>
              <td>
                <input
                  type="text"
                  name="caption"
                  maxlength="250"
                  required=""
                  id="id_caption"
                />
              </td>
            </tr>

            <tr>
              <th><label for="id_category">Category:</label></th>
              <td>
                <select name="category" required="" id="id_category">
                  <option value="" selected="">---------</option>

                  <option value="1">Profile</option>

                  <option value="2">Pets</option>
                </select>
              </td>
            </tr>
          </tbody>
        </table> -->
        <br /><br />
        <input type="submit" class="buttons" value="Add Photo" />
      </form>
    </div>
    <div class="usersPhotos">
      {% for ph in photos %}
      <a href="{% url 'post_create' user_id ph.id %}" class="card"
        ><div class="card">
          <img
            src="{{ ph.url}}"
            alt="{{ ph.caption }}"
            srcset=""
            id="usersPhotos"
          />
          <div class="card-content">
            <p>{{ ph.caption }}</p>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</main>

{% endblock %}

main_app/templates/picture_comment.html
{% extends 'base.html' %} {% block content %}
<div class="full-page-comment">
  <div class="comment-page">
    {% if username.username == photos.user.username %}
    <a href="{% url 'photo_delete' user_id photos.id %}" id="delete-post">Delete</a>
    {% endif %}
    <img class="image-comment" src="{{ photos.url }}" alt="" />
    <div class="post-comment">
      <div class="lower-post-comment">
        {% for post in posts %}
        <p>
          {{ post.caption }} {% if post.user_id == user_id %}
          <a
            href="{% url 'post_create_delete' user_id post.id photo_id %}"
            class="btn btn-outline-danger local-btn"
            >Delete</a
          >

          {% if post.like_by_user %}
          <span class="name likes"> Total Likes: {{ post.total_likes }}</span>
          {% else %}
          <span class="name likes"> Total Likes: {{ post.total_likes }}</span>
          {% endif %} {% else %} {% if post.like_by_user %}
          <a
            href="{% url 'like_create_delete' user_id post.id photo_id %}"
            class="btn btn-danger local-btn"
            >Liked</a
          >
          <span class="name likes"> Total Likes: {{ post.total_likes }}</span>
          {% else %}
          <a
            href="{% url 'like_create_delete' user_id post.id photo_id %}"
            class="btn btn-outline-danger local-btn"
            >Like</a
          >
          <span class="name likes"> Total Likes: {{ post.total_likes }}</span>
          {% endif %} {% endif %}
          <br />
          <span class="name">Posted By: {{ post.first_name }}</span> <br />
          <span class="date">on: {{ post.date|date:'Y-m-d' }}</span>
        </p>
        {% endfor %}
      </div>
      
    </div>
    <div id="post-caption"><h5>{{photos.user.username}} :</h5><h5>{{photos.caption}}</h5></div>
    <div class="comment-insert">
        <form
          id="comment-textarea"
          action="{% url 'post_create_comment' user_id photo_id %}"
          method="post"
        >
          <textarea
            name="comment"
            class="comment-write"
            cols="30"
            rows="10"
            maxlength="100"
          ></textarea>
    
          <button class="comment-submit">Submit</button>
        </form>
    </div>
  </div>

  
</div>


<script>
  let btn = document.querySelector(".btn");
  btn.onclick = function () {
    btn.classList.toggle("active");
  };

  let sidebar = document.querySelector(".lower-post-comment");

  let toppy = localStorage.getItem("sidebar-scroll");
  if (toppy !== null) {
    sidebar.scrollTop = parseInt(toppy, 10);
  }

  window.addEventListener("beforeunload", () => {
    localStorage.setItem("sidebar-scroll", sidebar.scrollTop);
  });
</script>
{%endblock %}